### PR TITLE
Additional info

### PR DESCRIPTION
**Pull request by Ethroes**
Added more information to the description to help the text fill up the page.

### CODE REVIEW

**Comment by Ethroes** [comment]
Also, I would like to delete the page "about our robot" as it's currently redundant with "Robots and Awards" and the homepage video. Not to mention that it's also out-of-date

**Comment by murraybd** [comment]
I think it is best to deal with one issue at a time, and as such I think the "about our robot" conversation should happen independently of this pull.

The changes in this look fine, my only concern is how often will this information need to be updated? I know the number of teams participating in Worlds changed last year. Do the weight limitations change often? I am worried about the pages becoming out of date and the regular maintenance burden of these changes.

Maybe we should have a checklist of pages to update if something about the competition changes, or perhaps just be non-specific about details regarding dynamic parts of FIRST.

**Comment by Ethroes** [comment]
The nit picky information contained in this description will only be updated at most once per year, I think it will be fine. Also, the specifics provided about the robots in general haven't change in the last 18 years and probably won't within the next 5 years. Even if they do, they're still important to have as a scale of reference for the reader who by all intents and purposes, will be completely new to FIRST Robotics.

**Comment by murraybd** [comment]
Okay, I just want to make sure that we are thinking about the maintenance requirements (in terms of regular updates) of changes that we make to the web site.

**Pull request merged**
