### PR TITLE
Added World Championships for 2016

### PR DESCRIPTION
**Pull request by Ethroes**

### CODE REVIEW

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
This looks good, but look at the Awards page I wonder if the items in the CAIS District event should be modified so that the robot's placement, e.g. Winner, should be first so it is consistent with the other events.

**Comment by murraybd** [comment]
Whoops, sorry about that.

**Comment by Ethroes** [comment]
Chairman's is listed above district winner on blue alliance due to its
prestige. I believe it should continue to stand above here.

On Mon, May 2, 2016 at 5:46 PM, Brian Murray notifications@github.com
wrote:

> Merged #35 https://github.com/TeamMeanMachine/Website/pull/35.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/TeamMeanMachine/Website/pull/35#event-648310642

## 

Brandon Murray

**Pull request merged**
